# Generated by Django 4.0.1 on 2022-01-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babycare',
            name='image',
            field=models.ImageField(default='/care/And still I rise.jpeg', upload_to='care'),
        ),
        migrations.AddField(
            model_name='babyhealth',
            name='image',
            field=models.ImageField(default='/physician/And still I rise.jpeg', upload_to='physician'),
        ),
    ]
