# Generated by Django 4.0.1 on 2022-01-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_babycare_image_babyhealth_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babycare',
            options={'ordering': ['agent_full_name'], 'verbose_name_plural': 'Babies Care'},
        ),
        migrations.AlterModelOptions(
            name='babycarecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Baby Care Categories'},
        ),
        migrations.AlterModelOptions(
            name='babyhealth',
            options={'ordering': ['full_name'], 'verbose_name_plural': 'Babies Health'},
        ),
        migrations.AlterField(
            model_name='babycare',
            name='care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='baby_care', to='care.babycarecategory'),
        ),
    ]
