# Generated by Django 4.0.1 on 2022-01-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTipsForBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.URLField(help_text='Link to an Image File')),
                ('message', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Tips',
                'verbose_name_plural': 'Health Tips for Babies',
                'ordering': ['-timeStamp'],
            },
        ),
    ]
